import type { CefrBand } from "./assessment-engine";
import type { QuestionType, TestPack } from "./test-packs";

type QuestionSeed = {
  type: QuestionType;
  prompt: string;
  correct: string;
  distractors: readonly [string, string, string];
};

type PackSeed = Omit<TestPack, "questions"> & {
  questions: readonly QuestionSeed[];
};

const q = (
  type: QuestionType,
  prompt: string,
  correct: string,
  distractorA: string,
  distractorB: string,
  distractorC: string,
): QuestionSeed => ({
  type,
  prompt,
  correct,
  distractors: [distractorA, distractorB, distractorC],
});

function makePack(seed: PackSeed): TestPack {
  const counts: Record<QuestionType, number> = {
    vocabulary: 0,
    sentence: 0,
    discourse: 0,
  };
  const labels: Record<QuestionType, string> = {
    vocabulary: "语境词汇",
    sentence: "句子理解",
    discourse: "语篇理解",
  };

  return {
    ...seed,
    questions: seed.questions.map((question) => {
      counts[question.type] += 1;
      return {
        id: `${seed.id}-${question.type[0]}${counts[question.type]}`,
        type: question.type,
        eyebrow: `${labels[question.type]} · ${counts[question.type]}/2`,
        prompt: question.prompt,
        options: [question.correct, ...question.distractors],
        correct: 0,
      };
    }),
  };
}

export const EXTRA_TEST_PACKS = {
  A1: [
    makePack({
      id: "a1-c-rainy-school-day",
      version: "C",
      band: "A1",
      title: "A rainy school day",
      dek: "A simple message about changes at school.",
      readTime: "约 1 分钟",
      paragraphs: [
        "It is raining today. The school sports day cannot be in the playground, so students will have games inside the school hall.",
        "Class One should go to the hall at ten o’clock. Students need clean sports shoes and a bottle of water. They do not need hats.",
        "Lunch is at twelve as usual. The school bus will leave at four, thirty minutes later than on a normal Friday.",
      ],
      definitions: {
        raining: "正在下雨",
        playground: "操场",
        hall: "大厅；礼堂",
        clean: "干净的",
        bottle: "瓶子",
        usual: "通常的；平常的",
        leave: "离开；出发",
        later: "更晚",
      },
      questions: [
        q("vocabulary", "文中的 hall 是什么地方？", "学校礼堂", "学校花园", "公交车站", "午餐商店"),
        q("vocabulary", "文中的 usual 最接近什么意思？", "和平常一样的", "非常早的", "只在雨天的", "很困难的"),
        q("sentence", "Class One 几点去 hall？", "十点", "十二点", "三点半", "四点"),
        q("sentence", "学生不需要带什么？", "帽子", "水", "运动鞋", "午餐"),
        q("discourse", "为什么活动改到室内？", "因为正在下雨", "因为大厅很新", "因为午餐提前", "因为公交车坏了"),
        q("discourse", "哪一项是正确的？", "校车比平常晚三十分钟出发", "午餐改到十点", "学生必须穿帽子", "活动在操场举行"),
      ],
    }),
    makePack({
      id: "a1-d-toms-new-room",
      version: "D",
      band: "A1",
      title: "Tom’s new room",
      dek: "A short description of a bedroom.",
      readTime: "约 1 分钟",
      paragraphs: [
        "Tom has a new room in his family’s house. The room is small, but it has a big window. His bed is under the window.",
        "There is a desk next to the bed. Tom keeps his school books on the desk and his football under it. A blue lamp is beside the books.",
        "Tom likes the room because it is quiet. In the evening, he sits at the desk and draws pictures before he goes to sleep.",
      ],
      definitions: {
        window: "窗户",
        under: "在……下面",
        desk: "书桌",
        keeps: "放置；保存",
        lamp: "台灯",
        beside: "在……旁边",
        quiet: "安静的",
        draws: "画画",
      },
      questions: [
        q("vocabulary", "文中的 quiet 是什么意思？", "安静的", "明亮的", "昂贵的", "拥挤的"),
        q("vocabulary", "文中的 beside 最接近哪个意思？", "在旁边", "在外面", "在后面", "在中间"),
        q("sentence", "Tom 的床在哪里？", "在窗户下面", "在门旁边", "在书桌上面", "在足球旁边"),
        q("sentence", "足球放在哪里？", "书桌下面", "床上", "窗户旁", "书架里"),
        q("discourse", "Tom 晚上在房间里做什么？", "坐在书桌前画画", "和朋友踢足球", "在床上吃晚饭", "打开窗户唱歌"),
        q("discourse", "这篇文章主要介绍什么？", "Tom 的新房间", "Tom 的学校", "一次足球比赛", "一家家具店"),
      ],
    }),
    makePack({
      id: "a1-e-sunday-market",
      version: "E",
      band: "A1",
      title: "Sunday market",
      dek: "A short notice about a weekly market.",
      readTime: "约 1 分钟",
      paragraphs: [
        "The Sunday Market is in King Street every week. It starts at nine in the morning and finishes at two in the afternoon.",
        "People can buy bread, cheese, vegetables and flowers. Mrs Brown sells hot cakes near the front gate. One cake costs two pounds.",
        "There is no car park at the market. Visitors can take bus number seven or leave their bikes beside the bank.",
      ],
      definitions: {
        market: "市场",
        finishes: "结束",
        vegetables: "蔬菜",
        flowers: "花",
        sells: "售卖",
        gate: "大门",
        costs: "价格为",
        visitors: "访客",
        beside: "在……旁边",
      },
      questions: [
        q("vocabulary", "文中的 finishes 是什么意思？", "结束", "开始", "搬走", "休息"),
        q("vocabulary", "文中的 visitors 指什么人？", "来市场的人", "卖蛋糕的人", "银行职员", "公交车司机"),
        q("sentence", "市场几点开始？", "上午九点", "上午七点", "中午十二点", "下午两点"),
        q("sentence", "一个热蛋糕多少钱？", "两英镑", "七英镑", "九英镑", "十二英镑"),
        q("discourse", "没有汽车停车场时，文章建议访客怎么去？", "坐七路公交或骑自行车", "只能够步行", "坐火车到银行", "让卖家开车接送"),
        q("discourse", "哪一样东西没有被列为市场商品？", "书", "面包", "蔬菜", "花"),
      ],
    }),
  ],
  A2: [
    makePack({
      id: "a2-c-community-garden",
      version: "C",
      band: "A2",
      title: "The community garden",
      dek: "A notice inviting neighbours to grow food together.",
      readTime: "约 2 分钟",
      paragraphs: [
        "Last spring, people in Hill Road turned an empty piece of land into a community garden. Twelve families now grow tomatoes, beans and herbs there.",
        "The garden opens every day, but members usually work together on Saturday mornings. New members do not need gardening experience. They only need to bring gloves and share one hour of work each week.",
        "Some vegetables are taken home by members. The rest are given to a local food centre. This month, the group also plans to build a small rainwater tank.",
      ],
      definitions: {
        empty: "空的；闲置的",
        community: "社区",
        herbs: "香草",
        experience: "经验",
        gloves: "手套",
        share: "共同承担",
        local: "当地的",
        tank: "水箱",
      },
      questions: [
        q("vocabulary", "文中的 experience 最接近什么意思？", "做过某事获得的经验", "购买工具的钱", "空闲的土地", "每周的计划"),
        q("vocabulary", "文中的 local 表示什么？", "附近当地的", "只在春天的", "来自国外的", "非常大型的"),
        q("sentence", "新成员每周需要做什么？", "贡献一小时劳动", "购买十二种蔬菜", "每天早上到花园", "修建一个食品中心"),
        q("sentence", "没有被成员带回家的蔬菜会怎样？", "送给当地食品中心", "留在地里不采", "卖给新成员", "用来换手套"),
        q("discourse", "这个花园项目的主要特点是什么？", "邻居共同种植并分享成果", "一家公司雇人种菜", "学生学习出售食品", "游客参观私人农场"),
        q("discourse", "文章最后提到的新计划是什么？", "建造雨水收集水箱", "扩大停车场", "周日关闭花园", "种植更多花朵"),
      ],
    }),
    makePack({
      id: "a2-d-lost-wallet",
      version: "D",
      band: "A2",
      title: "The lost wallet",
      dek: "A short story about returning something valuable.",
      readTime: "约 2 分钟",
      paragraphs: [
        "Nora was walking home from the cinema when she found a brown wallet near a bus stop. It contained some money, two bank cards and a library card.",
        "The library card had a name on it, so Nora took the wallet to the library the next morning. A librarian checked the computer and called the owner, Mr Lee.",
        "Mr Lee arrived twenty minutes later. He was relieved because he needed one of the cards for a work trip. He offered Nora some money, but she asked him to donate it to the library instead.",
      ],
      definitions: {
        wallet: "钱包",
        contained: "里面装有",
        librarian: "图书管理员",
        owner: "物主",
        relieved: "感到放心的",
        offered: "主动提出给予",
        donate: "捐赠",
        instead: "作为替代",
      },
      questions: [
        q("vocabulary", "文中的 relieved 最接近哪种感受？", "担心消除后的放心", "找到电影后的兴奋", "等待太久后的生气", "丢钱之后的尴尬"),
        q("vocabulary", "文中的 donate 是什么意思？", "捐赠", "借用", "隐藏", "检查"),
        q("sentence", "Nora 如何知道可以去哪里寻找钱包主人？", "她看到了图书证上的名字", "银行卡上写着地址", "公交司机认识主人", "电影院给她打了电话"),
        q("sentence", "Mr Lee 为什么特别需要其中一张卡？", "他要出差", "他要买电影票", "他要借一本书", "他要乘公交回家"),
        q("discourse", "Nora 最后如何处理 Mr Lee 提供的酬谢？", "请他把钱捐给图书馆", "自己收下了全部钱", "用来购买新钱包", "交给公交车司机"),
        q("discourse", "哪一句最能概括 Nora？", "她诚实并且为公共机构着想", "她经常丢失自己的物品", "她在图书馆工作", "她不喜欢帮助陌生人"),
      ],
    }),
    makePack({
      id: "a2-e-train-to-lakeside",
      version: "E",
      band: "A2",
      title: "Train to Lakeside",
      dek: "Travel information about a temporary timetable.",
      readTime: "约 2 分钟",
      paragraphs: [
        "Because workers are repairing the railway, trains from Central Station to Lakeside will use a different timetable this weekend.",
        "The first train leaves at 8:15, and then there is one train every hour until 6:15 in the evening. The journey will take seventy minutes instead of the usual fifty.",
        "Passengers for Green Hill must change to a free bus at North Station. Bicycles are allowed on trains after midday, but large groups should book places online before Friday.",
      ],
      definitions: {
        repairing: "修理",
        timetable: "时刻表",
        journey: "旅程",
        usual: "通常的",
        passengers: "乘客",
        change: "换乘",
        allowed: "被允许",
        book: "预订",
      },
      questions: [
        q("vocabulary", "文中的 timetable 是什么？", "交通班次时间表", "乘客名单", "铁路地图", "网上票价"),
        q("vocabulary", "文中的 book places 是什么意思？", "预订位置", "阅读书籍", "记录姓名", "改变车站"),
        q("sentence", "周末旅程需要多长时间？", "七十分钟", "五十分钟", "一小时", "八十五分钟"),
        q("sentence", "去 Green Hill 的乘客需要在哪里换免费公交？", "North Station", "Central Station", "Lakeside", "Green Hill"),
        q("discourse", "时刻表为什么临时改变？", "铁路正在维修", "车站举办活动", "乘客数量太少", "免费公交取消"),
        q("discourse", "哪类乘客应当在周五前网上预订？", "大型团体", "中午后的骑车人", "所有去 Lakeside 的人", "铁路维修工人"),
      ],
    }),
  ],
  B1: [
    makePack({
      id: "b1-c-library-of-things",
      version: "C",
      band: "B1",
      title: "A library of things",
      dek: "How one town lends equipment as well as books.",
      readTime: "约 3 分钟",
      paragraphs: [
        "When people hear the word library, they usually imagine shelves of books. In Bellford, however, the public library also lends tools, kitchen equipment and camping gear. Residents can borrow an electric drill, a cake tin or a tent for up to seven days.",
        "The service began after a survey showed that many households owned expensive objects they used only once or twice a year. Library staff believed that sharing such items could save money and reduce waste. Local volunteers check and clean everything before it is lent again.",
        "The most popular objects are carpet cleaners and gardening tools. Some users were initially worried about damaging borrowed equipment, so the library introduced short safety lessons. Since then, late returns have been a bigger problem than broken items.",
      ],
      definitions: {
        lends: "出借",
        gear: "设备；用具",
        residents: "居民",
        households: "家庭；住户",
        reduce: "减少",
        volunteers: "志愿者",
        initially: "起初",
        damaging: "损坏",
      },
      questions: [
        q("vocabulary", "文中的 gear 最接近什么意思？", "特定活动需要的设备", "图书馆的书架", "付给志愿者的钱", "居民调查结果"),
        q("vocabulary", "文中的 initially 表示什么？", "起初", "偶尔", "最近", "最终"),
        q("sentence", "图书馆为什么开始出借物品？", "调查发现许多贵重物品很少被使用", "居民不再愿意借书", "志愿者需要新的工作", "商店停止出售园艺工具"),
        q("sentence", "安全课程推出后，什么问题更突出？", "逾期归还", "物品损坏", "没有人借帐篷", "清洁费用过高"),
        q("discourse", "文章对共享物品服务的总体态度是什么？", "它有实际价值，也需要管理规则", "它比借书更危险，应当取消", "它只适合会修理工具的人", "它没有得到居民使用"),
        q("discourse", "第二段主要起什么作用？", "解释服务产生的原因和预期好处", "列出所有可以借的物品", "介绍安全课程的具体内容", "比较不同家庭的收入"),
      ],
    }),
    makePack({
      id: "b1-d-walking-meetings",
      version: "D",
      band: "B1",
      title: "Walking meetings",
      dek: "A workplace experiments with meetings outdoors.",
      readTime: "约 3 分钟",
      paragraphs: [
        "A small design company in Bristol has replaced some of its meeting-room discussions with walking meetings. Teams of two or three people follow a twenty-minute route through a nearby park while they talk about a single problem.",
        "The manager introduced the idea because afternoon meetings often felt slow and repetitive. After a six-week trial, most employees said they felt more alert outside and found it easier to speak honestly in a less formal setting. Several people also appreciated spending less time sitting.",
        "Walking meetings are not suitable for every task. Staff still use a room when they need to examine detailed images, include remote colleagues or make private decisions. The company therefore treats walking as an option rather than a rule.",
      ],
      definitions: {
        replaced: "取代",
        route: "路线",
        repetitive: "重复乏味的",
        trial: "试行",
        alert: "清醒专注的",
        formal: "正式的",
        suitable: "合适的",
        remote: "远程的",
      },
      questions: [
        q("vocabulary", "文中的 alert 最接近哪种状态？", "清醒并能集中注意力", "担心迷路", "身体非常疲惫", "对工作感到生气"),
        q("vocabulary", "文中的 trial 是什么意思？", "一段时间的试行", "一条公园路线", "一场法律审判", "一次员工面试"),
        q("sentence", "步行会议通常有多少人参加？", "两到三人", "一个人", "六到八人", "全公司员工"),
        q("sentence", "什么情况下员工仍然使用会议室？", "需要查看详细图像时", "只讨论一个问题时", "下午感到困倦时", "天气适合散步时"),
        q("discourse", "公司最终如何定位步行会议？", "一种可选择的会议形式", "所有会议的强制规定", "只给管理者的福利", "替代远程工作的工具"),
        q("discourse", "文章的结构最接近哪一种？", "介绍做法、报告效果、说明限制", "提出问题、指责员工、宣布处罚", "描述路线、比较公园、推荐旅游", "列出规则、解释法律、给出预算"),
      ],
    }),
    makePack({
      id: "b1-e-repair-cafe",
      version: "E",
      band: "B1",
      title: "Saturday repair café",
      dek: "Volunteers help neighbours repair everyday objects.",
      readTime: "约 3 分钟",
      paragraphs: [
        "On the first Saturday of each month, the town hall becomes a repair café. People bring broken lamps, small pieces of furniture, clothes and simple electronic devices. Volunteers with practical skills sit beside the owners and try to repair the objects together.",
        "The organisers are careful not to describe the event as a free repair shop. Owners are expected to watch, ask questions and do part of the work. The aim is not only to keep objects out of the rubbish but also to help people feel more confident about basic repairs.",
        "Not everything can be fixed. Replacement parts may be unavailable, and some electrical problems are too dangerous for volunteers to handle. Even then, visitors usually leave with an explanation of what failed and advice about what to do next.",
      ],
      definitions: {
        practical: "实际操作的",
        owners: "物主",
        expected: "被期待",
        confident: "有信心的",
        replacement: "替换用的",
        unavailable: "无法获得的",
        handle: "处理",
        failed: "出了故障",
      },
      questions: [
        q("vocabulary", "文中的 handle 最接近什么意思？", "处理", "携带", "出售", "隐藏"),
        q("vocabulary", "文中的 replacement parts 指什么？", "用来替换坏部件的新零件", "志愿者使用的桌子", "需要丢弃的旧衣服", "活动结束后的报告"),
        q("sentence", "为什么活动不被称为免费维修店？", "物主需要参与维修过程", "访客必须购买所有工具", "志愿者只修自己的东西", "活动只提供维修课程"),
        q("sentence", "即使物品没有修好，访客通常还能得到什么？", "故障解释和下一步建议", "一件全新的物品", "全部替换零件", "下个月的免费门票"),
        q("discourse", "维修咖啡馆有哪两个主要目标？", "减少浪费并提高居民维修信心", "销售工具并招聘志愿者", "收集电器并重新定价", "检查家具并制定法律"),
        q("discourse", "第三段主要说明什么？", "维修服务存在安全和材料限制", "活动地点经常改变", "志愿者缺乏实践技能", "电子产品最容易修好"),
      ],
    }),
  ],
  B2: [
    makePack({
      id: "b2-c-four-day-school-week",
      version: "C",
      band: "B2",
      title: "A four-day school week?",
      dek: "A district weighs savings against learning and family routines.",
      readTime: "约 4 分钟",
      paragraphs: [
        "Several rural school districts have moved classes from five shorter days to four longer ones. Supporters argue that closing buildings for an extra day reduces transport and heating costs, while the unusual schedule may help schools recruit teachers who would otherwise prefer jobs in larger towns.",
        "The financial case is less dramatic than it first appears. Salaries, which account for most school spending, rarely fall. Savings usually come from buses, meals and hourly staff, so districts often cut only a small percentage of their total budget. Families may also face new childcare costs on the free weekday.",
        "Evidence about learning is mixed. Older students sometimes benefit from having a full day for work or independent study, but younger children may struggle with longer classes. Results also depend on what schools provide on the fifth day. Optional tutoring can protect vulnerable pupils, whereas leaving families entirely on their own may widen existing gaps.",
        "The policy is therefore not a simple contest between innovation and tradition. Its value depends on local transport distances, labour markets, childcare options and the design of the day without classes.",
      ],
      definitions: {
        rural: "农村的；乡村的",
        recruit: "招聘",
        dramatic: "显著的；巨大的",
        account: "占据（比例）",
        vulnerable: "处境不利、需要支持的",
        widen: "扩大",
        entirely: "完全地",
        contest: "对立或竞争",
      },
      questions: [
        q("vocabulary", "文中的 vulnerable pupils 指什么？", "更可能因缺少支持而受影响的学生", "每天乘坐校车的所有学生", "希望去大城市工作的教师", "只参加独立学习的高年级学生"),
        q("vocabulary", "“salaries ... account for most school spending” 中 account for 是什么意思？", "构成大部分", "记录每一笔", "解释错误", "要求补偿"),
        q("sentence", "为什么四天制通常只能节省一小部分预算？", "占主要支出的工资通常不会减少", "学校必须购买更多公交车", "所有家庭都会获得托儿补贴", "教师只愿意领取小时工资"),
        q("sentence", "第五天提供可选辅导可能产生什么作用？", "减少弱势学生受到的不利影响", "保证所有学校关闭建筑", "让低年级学生上更长课程", "消除家庭的交通距离"),
        q("discourse", "作者的核心观点是什么？", "政策效果取决于当地条件和配套设计", "四天制在所有地区都能明显省钱", "传统五天制一定更适合儿童", "教师招聘是唯一需要考虑的因素"),
        q("discourse", "第二段在论证中承担什么功能？", "限制并细化节省成本这一主张", "证明学生成绩必然提高", "介绍四天制最早的历史", "比较不同教师的教学方法"),
      ],
    }),
    makePack({
      id: "b2-d-urban-shade",
      version: "D",
      band: "B2",
      title: "Who gets the shade?",
      dek: "Cities discover that cooling streets is also a question of distribution.",
      readTime: "约 4 分钟",
      paragraphs: [
        "As heatwaves become more frequent, cities are planting trees to cool streets and reduce energy use. A mature tree can shade buildings, lower surface temperatures and make walking safer. Yet counting the number of new trees tells only part of the story.",
        "Trees are not distributed evenly. Wealthier districts often have older, broader canopies, while neighbourhoods with dense housing and little private land may have the greatest need but the least available space. Planting a young tree also does not create immediate shade; it requires years of watering, protection and maintenance.",
        "Some cities now map afternoon temperatures together with age, income and access to public transport. This allows officials to identify places where heat exposure overlaps with social vulnerability. However, residents must still be consulted. A tree placed without discussion may block a shop sign, worsen allergies or occupy space needed for deliveries.",
        "An effective programme therefore treats shade as public infrastructure rather than decoration. Success should be measured not only by how many trees survive, but by whether cooling reaches people who are most exposed.",
      ],
      definitions: {
        mature: "成熟的",
        canopy: "树冠覆盖层",
        distributed: "被分布",
        maintenance: "维护",
        overlaps: "重叠",
        vulnerability: "脆弱处境",
        consulted: "被征求意见",
        infrastructure: "基础设施",
      },
      questions: [
        q("vocabulary", "文中的 canopy 指什么？", "树枝和树叶形成的覆盖层", "房屋使用的隔热材料", "公共交通线路图", "商店门前的遮阳布"),
        q("vocabulary", "“heat exposure overlaps with social vulnerability” 表示什么？", "高温风险与社会弱势在同一地区同时出现", "收入和温度使用相同的测量单位", "居民在热天更喜欢公共交通", "城市把树种在私人土地上"),
        q("sentence", "为什么新种树不能立即解决遮阴问题？", "树木需要多年生长和持续维护", "新树只能种在富裕地区", "所有幼树都会引发过敏", "法律禁止它们靠近建筑"),
        q("sentence", "作者为什么强调咨询居民？", "树木位置可能与当地实际使用发生冲突", "居民需要自己购买树木", "政府没有温度数据", "只有店主知道怎样浇水"),
        q("discourse", "作者建议怎样衡量项目成功？", "看降温是否惠及最暴露的人群", "只统计每年种了多少棵树", "比较不同社区的商店数量", "计算树木遮住了多少招牌"),
        q("discourse", "文章如何重新定义城市树木？", "从装饰转为公共基础设施", "从公共财产转为私人商品", "从降温工具转为交通设施", "从长期投资转为临时活动"),
      ],
    }),
    makePack({
      id: "b2-e-digital-tickets",
      version: "E",
      band: "B2",
      title: "When every ticket becomes digital",
      dek: "Convenient systems can quietly exclude people at the margins.",
      readTime: "约 4 分钟",
      paragraphs: [
        "Museums, trains and sports venues increasingly encourage visitors to use digital tickets. For organisations, the appeal is clear: electronic systems reduce printing, provide real-time attendance data and allow prices or entry times to be adjusted quickly.",
        "For most users, a phone-based ticket is convenient. But designing only for the majority can make a public service harder to use for people without smartphones, reliable internet or confidence with apps. A flat battery or a damaged screen can also turn a valid purchase into an argument at the entrance.",
        "Some organisations claim that a printable file is an adequate alternative. This still assumes access to a printer and the ability to navigate an online account. A more inclusive approach keeps at least one non-digital route, such as a staffed desk or a reusable physical card, and trains employees to resolve problems without treating users as suspicious.",
        "The broader lesson is not that digital systems should be rejected. It is that efficiency should be measured across the whole service, including the cost of exceptions, rather than only at the point where the average transaction becomes faster.",
      ],
      definitions: {
        venues: "场馆",
        appeal: "吸引力",
        adjusted: "被调整",
        adequate: "足够合适的",
        assumes: "预设；假定",
        inclusive: "包容不同人群的",
        suspicious: "可疑的",
        transaction: "交易；办理过程",
      },
      questions: [
        q("vocabulary", "文中的 adequate alternative 最接近什么意思？", "被认为足以替代原方式的选择", "费用最低的购票方法", "专门给员工使用的系统", "能够自动修理手机的服务"),
        q("vocabulary", "文中的 assumes 表明可打印文件方案有什么问题？", "它预设用户拥有某些资源和技能", "它证明打印一定更便宜", "它取消了所有在线账户", "它要求员工检查电池"),
        q("sentence", "为什么有效购买仍可能在入口处引发争执？", "手机可能没电或屏幕损坏", "电子票不会记录入场时间", "所有场馆都拒绝打印票", "票价无法在线调整"),
        q("sentence", "更包容的方案包含什么？", "至少保留一种非数字渠道", "强制所有人下载同一应用", "只允许员工打印文件", "取消现场问题处理"),
        q("discourse", "作者是否反对数字票？", "不反对，但要求把例外成本纳入效率评价", "完全反对，因为数字票没有优点", "完全支持，认为少数困难可以忽略", "态度不明，只讨论打印成本"),
        q("discourse", "第三段主要批评什么？", "表面替代方案仍可能隐藏数字门槛", "实体卡比智能手机更容易损坏", "员工没有实时出席数据", "博物馆调整入场时间"),
      ],
    }),
  ],
  C1: [
    makePack({
      id: "c1-c-museum-metrics",
      version: "C",
      band: "C1",
      title: "When museums optimise the measurable",
      dek: "Visitor metrics clarify performance while subtly redefining it.",
      readTime: "约 5 分钟",
      paragraphs: [
        "Museums increasingly use dashboards to monitor attendance, dwell time and the routes visitors take through exhibitions. Such data can expose neglected rooms, reveal confusing signs and help institutions allocate staff. The difficulty begins when measurements cease to inform judgment and start to substitute for it.",
        "A gallery evaluated primarily by visitor numbers has an incentive to favour recognisable subjects and highly shareable displays. A room containing demanding archival material may appear unsuccessful because fewer people enter and those who do move slowly. Yet hesitation can indicate concentration rather than dissatisfaction, while a rapid flow through a popular installation may reflect little more than a queue designed for photographs.",
        "The problem is not that quantitative evidence is false. It is that every metric compresses several possible experiences into a single comparable value. Once funding and promotion depend on that value, staff begin to reorganise exhibitions around what the instrument can register. The measure then participates in producing the behaviour it claims merely to describe.",
        "Responsible evaluation therefore requires friction between data and professional interpretation. Institutions should ask which experiences remain invisible to a metric, whose purposes the metric serves and what behaviour will become rational once employees know they are being assessed through it.",
      ],
      definitions: {
        dashboards: "汇总指标的仪表盘",
        dwell: "停留",
        allocate: "分配",
        substitute: "替代物",
        archival: "档案性的",
        compresses: "压缩、简化",
        register: "记录到",
        friction: "制衡性的张力",
      },
      questions: [
        q("vocabulary", "文中的 substitute for judgment 表示什么？", "指标取代而不再只是辅助专业判断", "数据为判断提供更多材料", "观众用照片代替参观", "员工重新解释档案"),
        q("vocabulary", "“what the instrument can register” 中 register 最接近什么意思？", "被测量工具捕捉和记录", "让观众登记身份", "正式注册一家机构", "表达公开反对"),
        q("sentence", "为什么参观者在档案展厅停留缓慢不一定是负面信号？", "犹豫和缓慢可能来自认真专注", "档案展厅总是比热门展览拥挤", "工作人员故意隐藏出口", "仪表盘不会记录停留时间"),
        q("sentence", "指标如何参与生产它所描述的行为？", "当奖惩依赖指标时，员工会围绕指标调整展览", "观众会主动修改仪表盘", "数据自动决定展品的历史意义", "资金越多，测量误差必然越小"),
        q("discourse", "作者对量化数据的立场是什么？", "数据有用，但必须与专业解释相互制衡", "数据天然虚假，应当完全放弃", "访问量足以衡量全部博物馆价值", "只有停留时间值得使用"),
        q("discourse", "文章的核心警告是什么？", "可测量性可能悄然重新定义机构追求的成功", "博物馆不应展示大众熟悉的主题", "拍照会使所有展览失去价值", "档案材料不适合公共展览"),
      ],
    }),
    makePack({
      id: "c1-d-politics-of-defaults",
      version: "D",
      band: "C1",
      title: "The politics hidden in defaults",
      dek: "A preset option can simplify choice while distributing power.",
      readTime: "约 5 分钟",
      paragraphs: [
        "Digital services routinely present one option as the default: notifications are enabled, data sharing is permitted or a subscription renews automatically unless the user intervenes. Defaults are often defended as conveniences that spare people from repeated minor decisions. That description is accurate but incomplete.",
        "A default does not remove choice; it assigns the cost of acting to one side. Users who accept the preset need do nothing, whereas those who prefer another arrangement must notice the option, understand its consequences and spend time changing it. Small frictions therefore accumulate unevenly, especially when interfaces are complex or attention is scarce.",
        "This does not mean that neutral design is available if only designers try harder. A form must begin in some state, and leaving every box empty can itself privilege delay or non-participation. The relevant question is consequently not whether a default influences behaviour, but whether that influence is justified by the user’s likely purpose and accompanied by a realistic route to refusal.",
        "Good governance of defaults combines evidence, reversibility and accountability. Organisations should explain whose interests the preset advances, test whether users understand it and make reversal proportionate to the ease with which the original commitment was made.",
      ],
      definitions: {
        routinely: "惯常地",
        intervenes: "主动干预",
        assigns: "分配",
        accumulate: "累积",
        scarce: "稀缺的",
        privilege: "使……获得优先地位",
        reversibility: "可逆性",
        proportionate: "相称的",
      },
      questions: [
        q("vocabulary", "文中的 privilege delay 是什么意思？", "让拖延或不参与在结构上更占优势", "给予用户特殊会员资格", "禁止用户立即修改设置", "要求设计师延迟发布"),
        q("vocabulary", "文中的 proportionate 强调什么？", "撤销难度应与最初承诺的容易程度相称", "所有选项必须具有相同颜色", "用户数量应与订阅价格一致", "默认设置必须按比例随机出现"),
        q("sentence", "作者说默认选项把行动成本分配给一方，是什么意思？", "反对预设的人必须承担发现、理解和修改的成本", "组织必须为每个用户支付费用", "接受默认的人需要填写更多表格", "设计师无法知道任何选项的后果"),
        q("sentence", "为什么把所有选项留空也不一定中立？", "它可能偏向拖延或不参与", "空白表格不能显示在屏幕上", "用户一定会随机选择", "法律要求每个表格都有默认值"),
        q("discourse", "作者判断默认设置正当性的主要标准是什么？", "是否符合用户可能的目的且提供真实可行的拒绝路径", "是否让组织获得最高收入", "是否减少页面上的文字数量", "是否得到所有用户一致同意"),
        q("discourse", "文章如何推进论证？", "先承认便利，再揭示成本分配，最后提出治理原则", "先否定所有默认，再推荐自动续费", "比较多个应用的颜色后选择最佳设计", "描述法律案例并拒绝任何结论"),
      ],
    }),
    makePack({
      id: "c1-e-replication-incentives",
      version: "E",
      band: "C1",
      title: "Why replication remains undervalued",
      dek: "Scientific institutions praise verification but often reward novelty.",
      readTime: "约 5 分钟",
      paragraphs: [
        "Science is commonly portrayed as self-correcting because findings can be tested again. Replication is central to that ideal: an independent team repeats a study or examines whether its conclusion survives a new population, method or setting. Nevertheless, the institutional rewards surrounding research often favour the first striking claim over the patient work of checking it.",
        "Journals compete for attention, universities count influential publications and funders seek projects that promise visible advances. A careful replication that confirms an existing result may be scientifically valuable while appearing administratively unoriginal. A failed replication can attract interest, but only after the initial claim has become prominent enough to make the contradiction newsworthy.",
        "These incentives shape more than career choices. They influence which uncertainties become documented. If verification is rarely funded, the published record contains many claims whose reliability has not been seriously challenged. Readers may mistake absence of contradiction for accumulation of support, although the relevant tests were never attempted.",
        "Improvement requires treating replication as infrastructure rather than remedial work performed after scandal. Dedicated funding, registered protocols and publication commitments made before results are known can reduce the pressure to produce a dramatic outcome. None guarantees truth, but together they make correction less dependent on exceptional individual persistence.",
      ],
      definitions: {
        replication: "重复验证研究",
        survives: "经受住检验",
        institutional: "制度层面的",
        prominent: "广受关注的",
        contradiction: "相矛盾的结果",
        reliability: "可靠性",
        remedial: "补救性的",
        protocols: "研究方案",
      },
      questions: [
        q("vocabulary", "文中的 administratively unoriginal 表示什么？", "在机构评价体系中显得缺乏新意", "研究方法在技术上完全相同", "行政人员亲自重复实验", "论文违反出版格式"),
        q("vocabulary", "“whether its conclusion survives” 中 survives 表示什么？", "结论在新检验中仍然成立", "研究团队获得长期职位", "论文没有被期刊删除", "实验对象保持健康"),
        q("sentence", "为什么没有出现反驳不等于获得了更多支持？", "相关验证可能根本没有得到资助或实施", "所有重复研究都会确认原结论", "读者不会看到失败研究", "初始研究通常没有任何结论"),
        q("sentence", "预先注册方案和出版承诺试图减少什么压力？", "必须制造戏剧性结果的压力", "使用独立团队的压力", "解释研究方法的压力", "在不同人群中测试的压力"),
        q("discourse", "作者建议如何重新理解重复验证？", "把它当作科学基础设施而非丑闻后的补救", "把它限制为失败研究的新闻报道", "交给个人在业余时间完成", "用引用次数代替重复实验"),
        q("discourse", "文章的主要因果链是什么？", "奖励偏好新颖性，导致验证不足并扭曲已知可靠性", "研究经费增加，必然产生更多矛盾", "期刊竞争减少，首次研究失去价值", "注册方案直接保证所有结论真实"),
      ],
    }),
  ],
  C2: [
    makePack({
      id: "c2-c-institutional-memory",
      version: "C",
      band: "C2",
      title: "The uses of institutional forgetting",
      dek: "Organisations need memory, yet selective forgetting can preserve their capacity to act.",
      readTime: "约 6 分钟",
      paragraphs: [
        "Institutional memory is usually invoked as an unqualified good. When experienced employees leave, organisations fear that tacit knowledge will vanish with them: why an apparently redundant procedure exists, which informal relationships sustain cooperation, or how a past emergency was contained. Archives, handover documents and mentoring schemes are intended to resist this loss.",
        "Yet perfect retention would not produce perfect judgment. Organisations also inherit obsolete categories, accommodations to circumstances that no longer exist and vivid memories of rare failures that distort later decisions. A rule introduced after one embarrassing incident may survive for decades because no successor wishes to assume responsibility for removing it. Memory then ceases to be a resource and becomes an alibi.",
        "Forgetting, in this context, need not mean accidental loss or deliberate concealment. It can describe the disciplined expiration of assumptions. Sunset clauses, periodic reauthorisation and exercises that require teams to justify a process without appealing to its ancestry all create opportunities for inherited knowledge to face present evidence.",
        "The difficulty is asymmetrical. The cost of preserving a useless rule is dispersed across thousands of minor delays, whereas the cost of deleting a useful safeguard may arrive suddenly and attach itself to an identifiable decision-maker. Institutions therefore remember defensively. Reform depends less on celebrating novelty than on distributing responsibility for revision so that forgetting does not look like individual recklessness.",
      ],
      definitions: {
        tacit: "难以言传的、默会的",
        redundant: "看似多余的",
        obsolete: "过时的",
        accommodations: "因应特定情境的安排",
        alibi: "推卸责任的借口",
        expiration: "到期失效",
        ancestry: "历史来源",
        asymmetrical: "不对称的",
      },
      questions: [
        q("vocabulary", "“memory ... becomes an alibi” 在文中是什么意思？", "历史被用作避免重新判断和承担责任的借口", "档案证明机构从未犯错", "员工用记忆替代书面文件", "过时规则保护了全部决策者"),
        q("vocabulary", "disciplined expiration of assumptions 指什么？", "通过制度安排让旧假设定期接受重新审查", "故意销毁所有历史档案", "员工自然忘记复杂流程", "紧急情况下暂停正常规则"),
        q("sentence", "为什么无用规则比有用保障更难删除？", "保留成本分散，而删除失误的责任集中且醒目", "无用规则通常没有书面记录", "有用保障从来不会产生延误", "继任者无法知道规则存在"),
        q("sentence", "sunset clauses 在论证中发挥什么作用？", "迫使继承的安排在到期时重新获得正当性", "确保规则永久保留", "隐藏过去的紧急事件", "把责任完全交给个人"),
        q("discourse", "作者对“制度记忆越多越好”的看法是什么？", "记忆必要，但未经审查的保留会固化过时判断", "完全赞同，因为遗忘必然危险", "完全反对，因为档案没有作用", "只适用于非正式关系"),
        q("discourse", "文章最后把改革的关键放在哪里？", "建立共同承担修订责任的机制", "鼓励个人冒险删除规则", "用新技术保存全部信息", "避免记录罕见失败"),
      ],
    }),
    makePack({
      id: "c2-d-moral-luck",
      version: "D",
      band: "C2",
      title: "Moral luck and public judgment",
      dek: "Outcomes sharpen accountability, but they can also obscure the quality of prior decisions.",
      readTime: "约 6 分钟",
      paragraphs: [
        "Public judgment often turns on consequences that decision-makers could influence but not control. Two officials may approve identical safety plans under identical evidence; an unforeseen failure occurs in one jurisdiction but not the other. The first is condemned as negligent, while the second is praised for prudence. Outcome has supplied information about the world, yet it has also rewritten perceptions of the earlier choice.",
        "This phenomenon is sometimes described as moral luck. The phrase does not imply that consequences are irrelevant. A realised harm creates victims, reveals vulnerabilities and may justify compensation regardless of the reasonableness of the initial decision. The mistake lies in allowing the outcome to monopolise evaluation, as though what eventually happened were fully available to those who acted beforehand.",
        "Attempts to correct hindsight bias by judging only procedures create an opposite danger. A bureaucracy can follow an immaculate checklist while remaining strategically obtuse, especially when its categories exclude weak signals that do not fit established reporting channels. Good evaluation must therefore ask both whether the process was reasonable given what was knowable and what the outcome teaches about the adequacy of that process.",
        "Accountability is strongest when these questions remain distinct. Sanctions for culpable disregard, compensation for suffered harm and institutional learning from revealed weakness need not rise or fall together. Collapsing them into a single verdict produces emotionally satisfying judgments at the cost of analytical precision.",
      ],
      definitions: {
        jurisdiction: "行政辖区",
        prudence: "审慎",
        monopolise: "独占",
        hindsight: "事后视角",
        immaculate: "无可挑剔的",
        obtuse: "迟钝、缺乏洞察的",
        culpable: "应受责备的",
        collapsing: "混为一体",
      },
      questions: [
        q("vocabulary", "文中的 strategically obtuse 最接近什么意思？", "程序正确却对重要风险缺乏洞察", "故意违反所有检查程序", "在政治上拒绝承担赔偿", "无法记录任何已知信息"),
        q("vocabulary", "outcome to monopolise evaluation 指什么？", "让最终结果成为评价的唯一决定因素", "把评估工作交给一个机构", "禁止受害者参与讨论", "只评估程序而忽略后果"),
        q("sentence", "为什么作者不主张完全忽略后果？", "后果会造成实际伤害并暴露制度弱点", "后果总能证明最初决策不合理", "程序评价在公共领域没有价值", "赔偿只取决于官员的动机"),
        q("sentence", "只按程序评价可能产生什么问题？", "完美清单可能仍排除无法归类的微弱信号", "程序会使所有结果完全相同", "官员会提前知道全部未来事件", "受害者会拒绝任何补偿"),
        q("discourse", "作者提出的评价框架是什么？", "区分可责性、损害补偿和制度学习", "根据结果对所有责任作统一判决", "只判断当时程序是否合规", "只比较两个地区的公众情绪"),
        q("discourse", "文章对 moral luck 的处理最准确的是？", "承认结果的重要性，同时限制其对先前判断的反向支配", "认为运气可以免除所有责任", "认为相同决策必须得到相同社会后果", "主张不应调查失败事件"),
      ],
    }),
    makePack({
      id: "c2-e-constitutional-ambiguity",
      version: "E",
      band: "C2",
      title: "Ambiguity as a constitutional resource",
      dek: "Indeterminacy can defer conflict, though the debt eventually falls on interpreters.",
      readTime: "约 6 分钟",
      paragraphs: [
        "Legal drafting is commonly praised for precision, and with good reason: citizens should be able to anticipate how public power may be used. Yet constitutional settlements sometimes depend on language whose boundaries are deliberately incomplete. Rival groups can endorse a shared formula not because they agree on every implication, but because the formula postpones questions that would otherwise prevent agreement altogether.",
        "Such ambiguity is not merely defective precision. It can function as a political resource, allowing institutions to accumulate practices before a contested principle is forced into a single doctrinal shape. Terms such as reasonable, proportionate or due process acquire content through cases, conventions and changing expectations. Their openness gives a settlement room to survive circumstances its authors could not specify.",
        "The same openness transfers power. When text underdetermines an answer, judges, administrators and later legislatures must supply one. Deferral at the founding moment consequently becomes discretion at a later moment, often exercised by actors who were not parties to the original bargain. Celebrating flexibility without identifying this transfer disguises a choice about institutional authority.",
        "The relevant contrast is therefore not between perfect clarity and careless vagueness. It is between different allocations of decision across time. Precision settles more in advance but risks brittleness; ambiguity preserves adaptability but incurs a debt of justification whenever an interpreter converts open language into binding action.",
      ],
      definitions: {
        settlements: "制度性安排或和解",
        implications: "潜在含义",
        doctrinal: "教义或法理体系上的",
        conventions: "惯例",
        underdetermines: "不足以唯一决定",
        discretion: "裁量权",
        brittleness: "僵脆性；缺乏适应力",
        incurs: "招致；承担",
      },
      questions: [
        q("vocabulary", "文中的 underdetermines an answer 是什么意思？", "文本提供的信息不足以唯一决定答案", "法律明确禁止某种回答", "解释者没有权力作出判断", "原作者忘记写下结论"),
        q("vocabulary", "incurs a debt of justification 表示什么？", "解释者把开放语言变成约束行动时必须说明理由", "国家需要支付立法费用", "模糊条款会自动失效", "法官必须遵守原作者的私人意见"),
        q("sentence", "为什么竞争群体可能共同接受一个模糊公式？", "它推迟了会阻碍当下达成协议的争议", "它保证所有人对后果理解相同", "它取消了未来解释的需要", "它把所有问题交给原作者"),
        q("sentence", "模糊性如何转移权力？", "后来的解释者获得补充文本未决内容的裁量", "公民获得修改宪法文本的直接权力", "创制者可以永久控制未来案件", "行政机构不再受到任何语言约束"),
        q("discourse", "作者认为真正的取舍是什么？", "在不同时点和机构之间分配决定权", "在准确法律和错误法律之间选择", "在法官和公民之间选择唯一主权者", "在书面文本和口头惯例之间二选一"),
        q("discourse", "文章对宪法模糊性的总体立场是什么？", "它有适应价值，但必须正视后续裁量与论证责任", "它只是低质量起草，应全部消除", "它总能保护少数群体", "它比精确规则更民主且没有代价"),
      ],
    }),
  ],
} satisfies Record<
  CefrBand,
  readonly [TestPack, TestPack, TestPack]
>;
