import type { CefrBand } from "./assessment-engine";

export type QuestionType = "vocabulary" | "sentence" | "discourse";

export type Question = {
  id: string;
  type: QuestionType;
  eyebrow: string;
  prompt: string;
  options: string[];
  correct: number;
};

export type TestPack = {
  id: string;
  version: "A" | "B";
  band: CefrBand;
  title: string;
  dek: string;
  readTime: string;
  paragraphs: string[];
  definitions: Record<string, string>;
  questions: Question[];
};

export const TEST_PACKS: Record<CefrBand, readonly [TestPack, TestPack]> = {
  A1: [
    {
      id: "a1-a-lunch-place",
      version: "A",
      band: "A1",
      title: "A new lunch place",
      dek: "A simple notice about a café near a school.",
      readTime: "约 1 分钟",
      paragraphs: [
        "Green Café is next to West School. It opens at eleven in the morning and closes at six in the evening.",
        "The café has sandwiches, soup, fruit and tea. A sandwich is four dollars. Soup is three dollars. Students get a free apple with lunch on Friday.",
        "There are six tables inside and four tables in the garden. Please do not bring dogs into the café.",
      ],
      definitions: {
        next: "紧挨着；在……旁边",
        opens: "开门；开始营业",
        closes: "关门；停止营业",
        sandwiches: "三明治（复数）",
        soup: "汤",
        fruit: "水果",
        free: "免费的",
        inside: "在里面",
        garden: "花园",
        bring: "带来",
      },
      questions: [
        {
          id: "a1a-v1",
          type: "vocabulary",
          eyebrow: "语境词汇 · 1/2",
          prompt: "文中的 free 最接近什么意思？",
          options: ["新鲜的", "免费的", "很小的", "星期五的"],
          correct: 1,
        },
        {
          id: "a1a-v2",
          type: "vocabulary",
          eyebrow: "语境词汇 · 2/2",
          prompt: "文中的 closes 最接近什么意思？",
          options: ["停止营业", "开始做饭", "卖完水果", "打扫桌子"],
          correct: 0,
        },
        {
          id: "a1a-s1",
          type: "sentence",
          eyebrow: "句子理解 · 1/2",
          prompt: "“Green Café is next to West School.” 是什么意思？",
          options: ["咖啡馆在学校里面。", "咖啡馆在学校旁边。", "学校下午关门。", "学校里有花园。"],
          correct: 1,
        },
        {
          id: "a1a-s2",
          type: "sentence",
          eyebrow: "句子理解 · 2/2",
          prompt: "学生星期五买午餐会得到什么？",
          options: ["一杯茶", "一碗汤", "一个苹果", "一张桌子"],
          correct: 2,
        },
        {
          id: "a1a-d1",
          type: "discourse",
          eyebrow: "语篇理解 · 1/2",
          prompt: "这篇文字主要介绍什么？",
          options: ["一所学校", "一家咖啡馆", "一座花园", "一只狗"],
          correct: 1,
        },
        {
          id: "a1a-d2",
          type: "discourse",
          eyebrow: "语篇理解 · 2/2",
          prompt: "哪一项是正确的？",
          options: ["咖啡馆早上八点开门。", "汤比三明治贵。", "咖啡馆里面有六张桌子。", "顾客可以带狗进去。"],
          correct: 2,
        },
      ],
    },
    {
      id: "a1-b-mia-saturday",
      version: "B",
      band: "A1",
      title: "Mia’s Saturday",
      dek: "A short story about one day in town.",
      readTime: "约 1 分钟",
      paragraphs: [
        "Mia gets up at eight on Saturday. She eats bread and an egg for breakfast. Then she takes a bus to the town library.",
        "At the library, Mia reads a book about birds. At twelve, she meets her friend Leo. They eat noodles in a small restaurant.",
        "In the afternoon, they walk in the park. Mia goes home at five because she has dinner with her family.",
      ],
      definitions: {
        breakfast: "早餐",
        takes: "乘坐；搭乘",
        library: "图书馆",
        birds: "鸟（复数）",
        meets: "见到；会面",
        noodles: "面条",
        restaurant: "餐馆",
        afternoon: "下午",
        because: "因为",
        family: "家人；家庭",
      },
      questions: [
        {
          id: "a1b-v1",
          type: "vocabulary",
          eyebrow: "语境词汇 · 1/2",
          prompt: "文中的 library 是什么地方？",
          options: ["图书馆", "车站", "餐馆", "公园"],
          correct: 0,
        },
        {
          id: "a1b-v2",
          type: "vocabulary",
          eyebrow: "语境词汇 · 2/2",
          prompt: "文中的 because 表示什么关系？",
          options: ["时间", "原因", "地点", "数量"],
          correct: 1,
        },
        {
          id: "a1b-s1",
          type: "sentence",
          eyebrow: "句子理解 · 1/2",
          prompt: "Mia 怎样去图书馆？",
          options: ["走路", "骑车", "坐公交车", "坐火车"],
          correct: 2,
        },
        {
          id: "a1b-s2",
          type: "sentence",
          eyebrow: "句子理解 · 2/2",
          prompt: "Mia 和 Leo 中午吃了什么？",
          options: ["面包", "面条", "鸡蛋", "水果"],
          correct: 1,
        },
        {
          id: "a1b-d1",
          type: "discourse",
          eyebrow: "语篇理解 · 1/2",
          prompt: "文章按照什么顺序写 Mia 的一天？",
          options: ["价格顺序", "时间顺序", "地点大小", "人物年龄"],
          correct: 1,
        },
        {
          id: "a1b-d2",
          type: "discourse",
          eyebrow: "语篇理解 · 2/2",
          prompt: "Mia 下午五点为什么回家？",
          options: ["图书馆关门了。", "她要和家人吃晚饭。", "Leo 要去坐公交。", "公园里开始下雨。"],
          correct: 1,
        },
      ],
    },
  ],
  A2: [
    {
      id: "a2-a-library-things",
      version: "A",
      band: "A2",
      title: "The library of things",
      dek: "A familiar community service with more than books.",
      readTime: "约 2 分钟",
      paragraphs: [
        "The Hill Street Library now lends more than books. People can borrow tools, board games, cake tins and small camping tents. The service is called the Library of Things.",
        "Members pay ten dollars each year. They can keep most items for one week. This is useful for people who need a tool for one small job but do not want to buy it. It also helps families try a new hobby without spending much money.",
        "The most popular item is a drill. On weekends, all six drills are often borrowed. Members must return items clean and tell the library if something is broken.",
      ],
      definitions: {
        lends: "借出",
        borrow: "借用",
        tools: "工具",
        tents: "帐篷",
        members: "会员",
        items: "物品",
        useful: "有用的",
        spending: "花费（金钱）",
        drill: "电钻",
        return: "归还",
      },
      questions: [
        {
          id: "a2a-v1",
          type: "vocabulary",
          eyebrow: "语境词汇 · 1/2",
          prompt: "文中的 borrow 最接近什么意思？",
          options: ["短期借用", "马上购买", "学习制作", "免费赠送"],
          correct: 0,
        },
        {
          id: "a2a-v2",
          type: "vocabulary",
          eyebrow: "语境词汇 · 2/2",
          prompt: "文中的 item 指什么？",
          options: ["一名会员", "一件物品", "一笔年费", "一项工作"],
          correct: 1,
        },
        {
          id: "a2a-s1",
          type: "sentence",
          eyebrow: "句子理解 · 1/2",
          prompt: "会员通常可以借一件物品多长时间？",
          options: ["一天", "一个周末", "一周", "一年"],
          correct: 2,
        },
        {
          id: "a2a-s2",
          type: "sentence",
          eyebrow: "句子理解 · 2/2",
          prompt: "这项服务为什么对想尝试新爱好的家庭有帮助？",
          options: ["他们不用花很多钱购买设备。", "图书馆会替他们完成工作。", "所有东西都可以借一年。", "会员不需要归还物品。"],
          correct: 0,
        },
        {
          id: "a2a-d1",
          type: "discourse",
          eyebrow: "语篇理解 · 1/2",
          prompt: "文章的主要目的是什么？",
          options: ["介绍一种可以借用日常物品的图书馆服务。", "教读者怎样使用电钻。", "比较六家不同的图书馆。", "劝人们停止所有购物。"],
          correct: 0,
        },
        {
          id: "a2a-d2",
          type: "discourse",
          eyebrow: "语篇理解 · 2/2",
          prompt: "最后一段主要补充了什么信息？",
          options: ["图书馆的地址", "最受欢迎的物品和归还要求", "会员的年龄", "露营的最佳季节"],
          correct: 1,
        },
      ],
    },
    {
      id: "a2-b-roof-garden",
      version: "B",
      band: "A2",
      title: "A garden on the roof",
      dek: "Neighbours grow food above their apartment building.",
      readTime: "约 2 分钟",
      paragraphs: [
        "Last spring, people in River House made a garden on the roof of their apartment building. Before that, the roof was empty and very hot in summer.",
        "Twelve families now grow tomatoes, beans, herbs and flowers there. Each family looks after one small area. They share water and tools. On Sunday mornings, neighbours work together and children help remove old leaves.",
        "The garden gives the building fresh food, but it has another benefit. The plants keep part of the roof cooler on sunny days. The group cannot grow enough food for everyone, so their next plan is to add two more garden boxes.",
      ],
      definitions: {
        roof: "屋顶",
        apartment: "公寓",
        empty: "空的",
        herbs: "香草；调味植物",
        share: "共同使用；分享",
        remove: "移走；清除",
        benefit: "好处",
        cooler: "更凉爽的",
        enough: "足够的",
        add: "增加",
      },
      questions: [
        {
          id: "a2b-v1",
          type: "vocabulary",
          eyebrow: "语境词汇 · 1/2",
          prompt: "文中的 share water and tools 是什么意思？",
          options: ["出售水和工具", "共同使用水和工具", "把工具放进水里", "分别购买新工具"],
          correct: 1,
        },
        {
          id: "a2b-v2",
          type: "vocabulary",
          eyebrow: "语境词汇 · 2/2",
          prompt: "文中的 benefit 最接近什么意思？",
          options: ["问题", "计划", "好处", "费用"],
          correct: 2,
        },
        {
          id: "a2b-s1",
          type: "sentence",
          eyebrow: "句子理解 · 1/2",
          prompt: "居民通常什么时候一起在花园工作？",
          options: ["星期一晚上", "星期五下午", "星期六中午", "星期天早上"],
          correct: 3,
        },
        {
          id: "a2b-s2",
          type: "sentence",
          eyebrow: "句子理解 · 2/2",
          prompt: "植物怎样帮助这座楼？",
          options: ["让部分屋顶更凉爽。", "让楼变得更高。", "为所有人提供足够食物。", "让住户不再需要水。"],
          correct: 0,
        },
        {
          id: "a2b-d1",
          type: "discourse",
          eyebrow: "语篇理解 · 1/2",
          prompt: "这篇文章主要讲什么？",
          options: ["居民共同建设和使用屋顶花园。", "孩子们如何学习做饭。", "一栋新公寓的销售计划。", "夏天怎样修理屋顶。"],
          correct: 0,
        },
        {
          id: "a2b-d2",
          type: "discourse",
          eyebrow: "语篇理解 · 2/2",
          prompt: "为什么居民计划再增加两个种植箱？",
          options: ["现在的工具坏了。", "他们想种出更多食物。", "屋顶冬天太冷。", "十二户家庭要搬走。"],
          correct: 1,
        },
      ],
    },
  ],
  B1: [
    {
      id: "b1-a-dark-sky",
      version: "A",
      band: "B1",
      title: "The night the town went darker",
      dek: "A town changes its street lights and discovers the night sky.",
      readTime: "约 3 分钟",
      paragraphs: [
        "For years, the small town of Millford used bright white street lights all night. Shop owners liked them because the town centre looked busy even after the shops had closed. However, local astronomers said the light made it almost impossible to see more than a few stars.",
        "Last year, the council replaced many old lamps with warmer lights that point down at the road. It also reduced the brightness after midnight, when few people were outside. Some residents worried that darker streets would be unsafe, so the council tested the plan in one area first.",
        "After six months, police records showed no increase in night-time accidents or crime. Electricity use in the test area fell by nearly thirty percent. Residents also began to notice the sky. A local school started monthly star-watching evenings, and a small hotel now lends telescopes to guests.",
        "The change did not remove every unnecessary light. Signs and private buildings still brighten the sky. Yet the test showed that the town could save energy without turning every street completely dark. Millford now plans to change the remaining lamps over the next two years.",
      ],
      definitions: {
        astronomers: "天文学研究者",
        impossible: "不可能的",
        council: "地方议会；市政机构",
        replaced: "替换",
        brightness: "亮度",
        residents: "居民",
        records: "记录",
        increase: "增加",
        telescopes: "望远镜（复数）",
        remaining: "剩余的",
      },
      questions: [
        {
          id: "b1a-v1",
          type: "vocabulary",
          eyebrow: "语境词汇 · 1/2",
          prompt: "第二段中的 reduced 最接近什么意思？",
          options: ["降低了", "测量了", "修好了", "比较了"],
          correct: 0,
        },
        {
          id: "b1a-v2",
          type: "vocabulary",
          eyebrow: "语境词汇 · 2/2",
          prompt: "最后一段中的 remaining lamps 指什么？",
          options: ["已经拆掉的灯", "仍未更换的灯", "酒店里的灯", "居民购买的灯"],
          correct: 1,
        },
        {
          id: "b1a-s1",
          type: "sentence",
          eyebrow: "句子理解 · 1/2",
          prompt: "市政机构为什么先在一个区域测试计划？",
          options: ["他们没有足够的灯。", "居民担心较暗的街道不安全。", "酒店要求先获得望远镜。", "商店只在该区域营业。"],
          correct: 1,
        },
        {
          id: "b1a-s2",
          type: "sentence",
          eyebrow: "句子理解 · 2/2",
          prompt: "六个月后的记录说明了什么？",
          options: ["犯罪增加了三成。", "所有街灯都关闭了。", "能源使用下降，安全没有变差。", "居民不再喜欢观星。"],
          correct: 2,
        },
        {
          id: "b1a-d1",
          type: "discourse",
          eyebrow: "语篇理解 · 1/2",
          prompt: "文章的主要结论是什么？",
          options: ["更合理的街灯可以节能并减少光污染。", "小镇夜间不应该使用任何灯。", "酒店应负责管理所有街灯。", "明亮街道一定能减少犯罪。"],
          correct: 0,
        },
        {
          id: "b1a-d2",
          type: "discourse",
          eyebrow: "语篇理解 · 2/2",
          prompt: "第三段提到学校和酒店，主要为了说明什么？",
          options: ["改变灯光还带来了观星活动。", "学校支付了换灯费用。", "酒店反对新的计划。", "游客造成了更多光污染。"],
          correct: 0,
        },
      ],
    },
    {
      id: "b1-b-missed-train",
      version: "B",
      band: "B1",
      title: "What a missed train taught the station",
      dek: "Passenger reports lead to clearer travel information.",
      readTime: "约 3 分钟",
      paragraphs: [
        "When the 7:40 train from Northbridge changed platforms, an announcement played inside the station. Most regular passengers moved quickly, but several visitors stayed where they were and missed the train. They later complained that the message had been too fast and difficult to hear.",
        "At first, the railway company believed the problem was unusual. Then staff checked reports from the previous year and found forty-two similar complaints. The station had added more services, but its signs and announcement system had not changed. Important information was often given only once.",
        "The company tested three improvements. Platform changes appeared on larger screens, announcements were repeated more slowly, and a coloured line on the floor guided passengers to the correct stairs. During the four-week test, staff counted how many people asked for help or went to the wrong platform.",
        "Requests for help fell by almost half. The floor line was especially useful for visitors and for people who did not speak English confidently. The company decided to keep all three changes. The missed train was not simply one traveller’s mistake; it revealed a system that worked well only for people who already knew how to use it.",
      ],
      definitions: {
        platforms: "站台（复数）",
        announcement: "广播通知",
        regular: "经常乘坐的；固定的",
        complained: "投诉；抱怨",
        unusual: "不常见的",
        previous: "之前的",
        improvements: "改进措施",
        guided: "引导",
        confidently: "有信心地；熟练地",
        revealed: "揭示；显示出",
      },
      questions: [
        {
          id: "b1b-v1",
          type: "vocabulary",
          eyebrow: "语境词汇 · 1/2",
          prompt: "最后一段中的 revealed 最接近什么意思？",
          options: ["隐藏了", "解决了", "揭示了", "重复了"],
          correct: 2,
        },
        {
          id: "b1b-v2",
          type: "vocabulary",
          eyebrow: "语境词汇 · 2/2",
          prompt: "第三段中的 guided passengers 是什么意思？",
          options: ["向乘客收费", "引导乘客前进", "要求乘客等待", "记录乘客姓名"],
          correct: 1,
        },
        {
          id: "b1b-s1",
          type: "sentence",
          eyebrow: "句子理解 · 1/2",
          prompt: "铁路公司为什么改变了最初看法？",
          options: ["发现过去有很多类似投诉。", "火车停止了全部服务。", "旅客拒绝查看屏幕。", "工作人员听不懂广播。"],
          correct: 0,
        },
        {
          id: "b1b-s2",
          type: "sentence",
          eyebrow: "句子理解 · 2/2",
          prompt: "四周测试期间，公司统计了什么？",
          options: ["火车的速度", "车票的价格", "求助和走错站台的人数", "所有乘客的英语成绩"],
          correct: 2,
        },
        {
          id: "b1b-d1",
          type: "discourse",
          eyebrow: "语篇理解 · 1/2",
          prompt: "文章最想说明什么？",
          options: ["错过火车总是乘客自己的责任。", "观察真实困难可以帮助改善公共系统。", "车站应该取消广播。", "经常坐车的人最需要彩色路线。"],
          correct: 1,
        },
        {
          id: "b1b-d2",
          type: "discourse",
          eyebrow: "语篇理解 · 2/2",
          prompt: "文章按照怎样的结构展开？",
          options: ["人物介绍—旅行广告—价格比较", "问题出现—调查原因—测试改进—得出结果", "历史回顾—观点争论—未来预测", "提出规则—列出例外—取消规则"],
          correct: 1,
        },
      ],
    },
  ],
  B2: [
    {
      id: "b2-a-repair-cafes",
      version: "A",
      band: "B2",
      title: "Why repair cafés are spreading",
      dek: "A community response to throwaway culture.",
      readTime: "约 3 分钟",
      paragraphs: [
        "On a Saturday morning in Amsterdam, a broken lamp, a silent radio and a torn winter coat arrive at the same community hall. Their owners have not come to throw them away. They have come to a repair café, where volunteers help local people fix everyday objects for free.",
        "The idea began in the Netherlands in 2009 and has since spread to cities around the world. Supporters say repair cafés reduce waste, but that is only part of their appeal. Many visitors own objects that could technically be replaced at little cost. They bring them anyway because they want to understand how things work, meet neighbours, or preserve an item with personal value. Visitors also learn from one another: a person who arrives with a lamp may leave knowing how to replace a plug, sew a button, or identify a loose connection.",
        "Modern products, however, are not always designed to be repaired. Batteries may be glued inside devices, spare parts can be difficult to find, and opening a product may cancel its guarantee. These barriers mean that even skilled volunteers cannot save everything. Some cafés therefore record the objects they fail to repair and share the data with campaigns for stronger “right to repair” laws.",
        "The cafés do not claim that every old toaster deserves a second life. Their value lies less in rescuing each object than in changing how people think about ownership. A successful visit can turn a customer, who normally discards a broken product, into someone who first asks whether the problem can be understood and fixed.",
      ],
      definitions: {
        torn: "破损的；撕裂的",
        volunteers: "志愿者",
        preserve: "保留；维护，使其继续存在",
        glued: "被胶水粘住的",
        barriers: "障碍；阻碍事情发生的因素",
        guarantee: "保修；质量保证",
        campaigns: "有组织的倡议或行动",
        rescuing: "挽救；使某物免于被丢弃",
        ownership: "所有权；拥有某物的状态",
        discards: "丢弃；不要",
        appeal: "吸引力",
        technically: "严格来说；从技术角度看",
      },
      questions: [
        {
          id: "b2a-v1",
          type: "vocabulary",
          eyebrow: "语境词汇 · 1/2",
          prompt: "第三段中的 barriers 最接近什么意思？",
          options: ["维修工具", "阻碍维修的因素", "消费者的投诉", "产品的外壳"],
          correct: 1,
        },
        {
          id: "b2a-v2",
          type: "vocabulary",
          eyebrow: "语境词汇 · 2/2",
          prompt: "最后一段中的 discards 最接近什么意思？",
          options: ["重新设计", "仔细检查", "丢弃", "出售"],
          correct: 2,
        },
        {
          id: "b2a-s1",
          type: "sentence",
          eyebrow: "句子理解 · 1/2",
          prompt: "“Reduce waste, but that is only part of their appeal.” 最准确的意思是什么？",
          options: ["它们几乎不能减少垃圾。", "减少垃圾是唯一原因。", "除了减废，它们还有其他吸引力。", "支持者反对维修。"],
          correct: 2,
        },
        {
          id: "b2a-s2",
          type: "sentence",
          eyebrow: "句子理解 · 2/2",
          prompt: "“Their value lies less in rescuing each object than in changing how people think about ownership.” 是什么意思？",
          options: ["更重要的价值是改变人们对物品的看法。", "每件物品都必须修好。", "所有权比技术更昂贵。", "活动主要降低售价。"],
          correct: 0,
        },
        {
          id: "b2a-d1",
          type: "discourse",
          eyebrow: "语篇理解 · 1/2",
          prompt: "这篇文章的主旨是什么？",
          options: ["教授专业维修技术。", "解释维修咖啡馆流行的原因及影响。", "证明旧电器都应修复。", "比较各国保修法律。"],
          correct: 1,
        },
        {
          id: "b2a-d2",
          type: "discourse",
          eyebrow: "语篇理解 · 2/2",
          prompt: "第三段列举电池和零件，主要起什么作用？",
          options: ["展示维修面临的现实限制。", "说明志愿者没有技能。", "证明新品更便宜。", "介绍收费方式。"],
          correct: 0,
        },
      ],
    },
    {
      id: "b2-b-quiet-hour",
      version: "B",
      band: "B2",
      title: "The supermarket’s quiet hour",
      dek: "A small accessibility change reveals a wider design question.",
      readTime: "约 3 分钟",
      paragraphs: [
        "Every Tuesday afternoon, one branch of the Mason supermarket lowers its lights, turns off background music and stops making non-essential announcements. Staff avoid moving noisy carts, and checkout screens are dimmed. The store calls this period its “quiet hour.” It was introduced after several customers said ordinary shopping could feel overwhelming.",
        "The idea was first intended for autistic customers and people who are especially sensitive to sound or light. Yet the store soon noticed that others also preferred the calmer environment: older shoppers, parents with sleeping babies and customers recovering from illness. What began as a specialised adjustment turned out to have a much wider audience.",
        "Not everyone is satisfied. Some customers complain that the darker aisles make labels harder to read, while others cannot visit at the scheduled time. Disability groups have also warned that a single quiet hour can become an excuse for ignoring accessibility during the rest of the week. They argue that staff training, clear signs and flexible assistance matter just as much as reduced noise.",
        "The store has kept the weekly hour but now treats it as a test rather than a complete solution. It has replaced several beeping machines, reviewed the volume of announcements and trained staff to offer help without attracting unwanted attention. The experiment suggests that inclusive design is rarely about creating one separate experience for a small group. It is more often a process of noticing which features make an ordinary environment unnecessarily difficult—and asking how many of them are necessary at all.",
      ],
      definitions: {
        essential: "必要的；必不可少的",
        overwhelming: "令人难以承受的",
        autistic: "与自闭症相关的",
        sensitive: "敏感的",
        specialised: "专门的；针对特定群体的",
        adjustment: "调整；改动",
        scheduled: "预定安排的",
        accessibility: "无障碍程度；可使用性",
        flexible: "灵活的",
        inclusive: "包容不同人群的",
      },
      questions: [
        {
          id: "b2b-v1",
          type: "vocabulary",
          eyebrow: "语境词汇 · 1/2",
          prompt: "第一段中的 overwhelming 最接近什么意思？",
          options: ["令人难以承受的", "非常便宜的", "容易预测的", "没有必要的"],
          correct: 0,
        },
        {
          id: "b2b-v2",
          type: "vocabulary",
          eyebrow: "语境词汇 · 2/2",
          prompt: "最后一段中的 inclusive design 指什么？",
          options: ["只服务少数人的设计", "能够照顾不同人群需要的设计", "使商品更昂贵的设计", "完全安静的设计"],
          correct: 1,
        },
        {
          id: "b2b-s1",
          type: "sentence",
          eyebrow: "句子理解 · 1/2",
          prompt: "“A specialised adjustment turned out to have a much wider audience.” 表明什么？",
          options: ["安静时段只帮助自闭症顾客。", "原本针对特定人群的改变也帮助了很多其他人。", "多数顾客反对改变。", "商店决定延长营业时间。"],
          correct: 1,
        },
        {
          id: "b2b-s2",
          type: "sentence",
          eyebrow: "句子理解 · 2/2",
          prompt: "残障组织为什么认为一小时还不够？",
          options: ["他们希望商店停止销售商品。", "无障碍需求在一周其他时间也存在。", "灯光应该更亮而音乐更响。", "所有顾客都能在同一时间到店。"],
          correct: 1,
        },
        {
          id: "b2b-d1",
          type: "discourse",
          eyebrow: "语篇理解 · 1/2",
          prompt: "作者对“安静时段”的总体态度是什么？",
          options: ["毫无保留地认为它解决了所有问题。", "认为它有价值，但只是持续改善的起点。", "认为它只是一种营销骗局。", "认为普通超市不需要无障碍设计。"],
          correct: 1,
        },
        {
          id: "b2b-d2",
          type: "discourse",
          eyebrow: "语篇理解 · 2/2",
          prompt: "第三段在文章中主要承担什么功能？",
          options: ["介绍商店历史。", "补充该方案的限制和反方意见。", "解释商品如何定价。", "证明所有声音都有害。"],
          correct: 1,
        },
      ],
    },
  ],
  C1: [
    {
      id: "c1-a-friction",
      version: "A",
      band: "C1",
      title: "The hidden value of friction",
      dek: "A nuanced argument about convenience and deliberate action.",
      readTime: "约 4 分钟",
      paragraphs: [
        "Digital products are often praised for eliminating friction. A purchase that once required a trip to a shop can now be completed with a thumbprint; a programme chooses the next episode before the previous one has ended. In design language, every pause is liable to be treated as a defect—a moment in which the user might abandon the intended action.",
        "This pursuit of effortlessness has obvious benefits. Unnecessary forms, confusing menus and repetitive decisions consume attention without improving the outcome. Removing them can make services more accessible, particularly for people whose time, mobility or concentration is limited. Yet the assumption that all friction is waste quietly confuses two different things: obstacles that prevent an intention from being fulfilled, and pauses that allow an intention to be examined.",
        "Consider a platform that asks readers whether they truly want to share an article they have not opened. The additional step makes sharing marginally less efficient, but efficiency is not the only relevant measure. The pause makes a previously invisible choice salient. It creates a brief opportunity for deliberation, and may therefore improve the quality of the action even as it reduces its speed.",
        "The distinction matters because interfaces do not merely serve preferences; over time, they help produce them. When the path of least resistance is repeated often enough, an occasional impulse can harden into a routine. Defaults are especially powerful because they present one path as normal while making alternatives feel exceptional. A user may still be formally free to choose, yet the repeated convenience of one option can gradually narrow the range of actions that comes readily to mind. This does not mean that designers should make every task cumbersome. Deliberate inconvenience can easily become paternalistic, especially when an organisation imposes costs on users while exempting itself.",
        "A more defensible principle is to ask who benefits when a particular hesitation disappears. If removing a step helps users carry out a settled purpose, convenience is genuinely useful. If it mainly accelerates an action that benefits the platform—and leaves no space for reconsideration—then a small amount of friction may be less a design failure than a form of agency.",
      ],
      definitions: {
        friction: "阻力；使行动稍微变慢或变难的环节",
        liable: "很可能会；容易",
        effortlessness: "毫不费力的状态",
        fulfilled: "被实现；得到满足",
        marginally: "略微地",
        salient: "显著的；容易被注意到的",
        deliberation: "审慎思考；权衡",
        cumbersome: "麻烦而难以操作的",
        paternalistic: "以“为你好”为由限制选择的",
        exempting: "使……免除责任或成本",
        defensible: "能够被合理辩护的",
        agency: "自主判断和行动的能力",
      },
      questions: [
        {
          id: "c1a-v1",
          type: "vocabulary",
          eyebrow: "语境词汇 · 1/2",
          prompt: "第三段中的 salient 最接近什么意思？",
          options: ["更容易被注意到", "在法律上有效", "令人厌烦", "被永久保存"],
          correct: 0,
        },
        {
          id: "c1a-v2",
          type: "vocabulary",
          eyebrow: "语境词汇 · 2/2",
          prompt: "最后一段中的 agency 主要指什么？",
          options: ["平台代理机构", "提高效率的方法", "自主判断和行动的能力", "技术兼容性"],
          correct: 2,
        },
        {
          id: "c1a-s1",
          type: "sentence",
          eyebrow: "句子理解 · 1/2",
          prompt: "“The assumption that all friction is waste quietly confuses two different things” 指出什么？",
          options: ["混淆了软件与硬件。", "混淆了无意义阻碍与有助反思的停顿。", "用户把便利当成浪费。", "所有产品都故意增加步骤。"],
          correct: 1,
        },
        {
          id: "c1a-s2",
          type: "sentence",
          eyebrow: "句子理解 · 2/2",
          prompt: "“Interfaces do not merely serve preferences; over time, they help produce them.” 是什么意思？",
          options: ["界面只能展示已有偏好。", "界面无法预测偏好。", "界面既响应也塑造习惯与偏好。", "界面长期使用后才能运行。"],
          correct: 2,
        },
        {
          id: "c1a-d1",
          type: "discourse",
          eyebrow: "语篇理解 · 1/2",
          prompt: "作者的核心观点是什么？",
          options: ["删除全部步骤。", "让所有任务困难。", "便利只对平台有利。", "区分无意义障碍和保护审慎选择的停顿。"],
          correct: 3,
        },
        {
          id: "c1a-d2",
          type: "discourse",
          eyebrow: "语篇理解 · 2/2",
          prompt: "第四段讨论家长式干预，主要承担什么功能？",
          options: ["推翻前文。", "承认观点边界，避免把所有不便合理化。", "说明平台更有耐心。", "转向政府监管。"],
          correct: 1,
        },
      ],
    },
    {
      id: "c1-b-forecast",
      version: "B",
      band: "C1",
      title: "When a forecast changes the future",
      dek: "Predictions can influence the very outcomes they describe.",
      readTime: "约 5 分钟",
      paragraphs: [
        "Forecasts appear to describe a future that already exists somewhere ahead of us, waiting to be measured more accurately. A weather report predicts rain; an economic model estimates unemployment; an algorithm identifies customers likely to cancel a subscription. In each case, the forecast seems to stand outside the event, observing it from a distance. Yet many social predictions do not remain passive for long. Once published, they become part of the situation they claim merely to describe.",
        "Consider a report warning that a bank may be unstable. If enough customers believe it, they may withdraw their savings, creating the shortage the report predicted. The opposite can also occur. A reliable warning about a disease may persuade people to change their behaviour, causing the expected outbreak to remain small. When critics later point to the low number of cases as proof that the warning was exaggerated, they overlook the possibility that the forecast failed precisely because people acted on it.",
        "This feedback makes social prediction unusually difficult to evaluate. Accuracy cannot always be judged by comparing a statement with the outcome that followed, because the statement may have helped produce that outcome. Nor does influence make a forecast dishonest. A fire alarm is valuable not because the building is eventually destroyed, but because it prompts an evacuation. The relevant question is whether the warning was justified by the evidence available at the time and whether the response it encouraged was proportionate.",
        "Problems arise when forecasters benefit from the reactions they provoke. A company might announce a shortage to encourage immediate purchases, or a political campaign might present a narrow lead as inevitable in order to attract supporters. In such cases, prediction begins to resemble intervention. The language of neutral measurement can conceal an attempt to shape behaviour.",
        "We should therefore ask two questions whenever a public forecast concerns human action. How well does the available evidence support it? And how might announcing it alter the choices from which the eventual result will emerge? Treating forecasts as both descriptions and interventions does not make them useless. It makes us more precise about the kind of power they possess.",
      ],
      definitions: {
        passive: "被动的；不产生作用的",
        unstable: "不稳定的",
        withdraw: "取出；撤回",
        outbreak: "（疾病等的）爆发",
        exaggerated: "被夸大的",
        feedback: "反馈作用",
        proportionate: "与情况相称的",
        provoke: "引起；激起",
        inevitable: "不可避免的",
        intervention: "干预",
        conceal: "掩盖",
        eventual: "最终的",
      },
      questions: [
        {
          id: "c1b-v1",
          type: "vocabulary",
          eyebrow: "语境词汇 · 1/2",
          prompt: "第三段中的 proportionate 最接近什么意思？",
          options: ["与风险相称的", "被精确预测的", "完全免费的", "没有证据的"],
          correct: 0,
        },
        {
          id: "c1b-v2",
          type: "vocabulary",
          eyebrow: "语境词汇 · 2/2",
          prompt: "第四段中的 intervention 在文中指什么？",
          options: ["客观记录", "对行为的主动影响", "长期统计", "错误翻译"],
          correct: 1,
        },
        {
          id: "c1b-s1",
          type: "sentence",
          eyebrow: "句子理解 · 1/2",
          prompt: "为什么疫情预测“没有实现”不一定证明预测错误？",
          options: ["数据一定被隐藏了。", "人们可能因预警改变行为，从而减少病例。", "疾病预测从不需要证据。", "病例数量与预测无关。"],
          correct: 1,
        },
        {
          id: "c1b-s2",
          type: "sentence",
          eyebrow: "句子理解 · 2/2",
          prompt: "火警的例子说明了什么？",
          options: ["警告的价值可能在于促成避免坏结果的行动。", "所有预测都应制造恐慌。", "建筑最终必须被烧毁。", "准确性完全不重要。"],
          correct: 0,
        },
        {
          id: "c1b-d1",
          type: "discourse",
          eyebrow: "语篇理解 · 1/2",
          prompt: "文章的中心论点是什么？",
          options: ["社会预测只是对未来的中立描述。", "社会预测可能改变被预测的结果，因此要同时评估证据与影响。", "公开预测都不诚实。", "经济模型比天气预报更准确。"],
          correct: 1,
        },
        {
          id: "c1b-d2",
          type: "discourse",
          eyebrow: "语篇理解 · 2/2",
          prompt: "第四段在论证中增加了哪一层问题？",
          options: ["预测者可能利用预测引发的反应获利。", "所有银行都会倒闭。", "疾病预测没有作用。", "公众不应该看到任何数据。"],
          correct: 0,
        },
      ],
    },
  ],
  C2: [
    {
      id: "c2-a-forgetting-archive",
      version: "A",
      band: "C2",
      title: "The archive that learned to forget",
      dek: "A reflection on memory, omission and institutional responsibility.",
      readTime: "约 6 分钟",
      paragraphs: [
        "Archives are conventionally praised for resisting disappearance. They rescue documents from damp cupboards, preserve recordings whose original machinery has become obsolete, and impose enough order on private papers that strangers may consult them decades later. Against the fragility of individual memory, the archive promises durable evidence. It is tempting, therefore, to imagine that its ethical task is simply to retain as much as possible.",
        "That ideal becomes less innocent when storage is cheap and retrieval is automated. A local authority may preserve every complaint, address and medical detail contained in an old case file; a school may keep disciplinary records long after the behaviour they describe has ceased to matter. Information collected for one purpose can later be searched, combined and interpreted for another. What looks like responsible preservation from the institution’s perspective may feel like an indefinitely extended sentence to the person represented in the record.",
        "Some archivists have begun to discuss “deliberate forgetting”: not the careless loss of material, nor the destruction of evidence that powerful organisations would prefer to hide, but the planned removal or restriction of records whose continuing availability produces more harm than public value. The phrase is deliberately uncomfortable. Archives have often been damaged by censorship, colonial extraction and official secrecy, so any invitation to discard material deserves suspicion. Yet a refusal to distinguish among records can also disguise a choice. Keeping everything privileges future researchers over people who must live under the permanent visibility of their past.",
        "The difficulty is that the value of a record changes with context. A minor offence may be irrelevant to an employer but essential to a historian studying discriminatory policing. A photograph freely donated to a community project may become painful when facial-recognition software makes every person in it identifiable. No universal expiry date can resolve such conflicts. Decisions require attention to consent, power, the sensitivity of the material and the realistic—not merely imaginable—benefits of continued access.",
        "Deliberate forgetting should therefore be understood less as deletion than as a range of carefully governed limits. A name can be hidden while an event remains documented. Access can be delayed, granted only for defined purposes or reconsidered when technology changes what can be inferred. Crucially, the people described by records can be given a voice in deciding their future. Such measures complicate the fantasy of the archive as a neutral container. But neutrality was always a fantasy: selecting, describing and preserving are already interventions.",
        "An archive earns trust not by remembering without limit, but by being able to explain why it remembers, for whom, and at whose cost. Sometimes integrity requires protecting a trace from erasure. At other times, it requires refusing to turn preservation into perpetual exposure. The mature archive does not choose memory over forgetting once and for all; it accepts responsibility for drawing, defending and revising the boundary between them.",
      ],
      definitions: {
        obsolete: "淘汰的；不再使用的",
        durable: "持久的",
        innocent: "无害的；此处指不带问题的",
        indefinitely: "无限期地",
        censorship: "审查制度",
        extraction: "攫取；抽取",
        privileges: "使……处于优先地位",
        expiry: "到期；失效",
        governed: "受到规则约束的",
        inferred: "被推断出的",
        neutrality: "中立性",
        perpetual: "永久持续的",
      },
      questions: [
        {
          id: "c2a-v1",
          type: "vocabulary",
          eyebrow: "语境词汇 · 1/2",
          prompt: "第三段中的 privileges future researchers 最接近什么意思？",
          options: ["剥夺研究者资格", "把未来研究者的利益置于更优先位置", "要求研究者公开身份", "让研究资料失去价值"],
          correct: 1,
        },
        {
          id: "c2a-v2",
          type: "vocabulary",
          eyebrow: "语境词汇 · 2/2",
          prompt: "最后一段中的 perpetual exposure 指什么？",
          options: ["档案长期受到阳光照射", "个人过去永久处于可被查看的状态", "研究人员不断更换", "文件材料自然老化"],
          correct: 1,
        },
        {
          id: "c2a-s1",
          type: "sentence",
          eyebrow: "句子理解 · 1/2",
          prompt: "“A refusal to distinguish among records can also disguise a choice.” 最准确的理解是什么？",
          options: ["保存一切看似中立，实际上也偏向了某些利益。", "档案员无法区分纸质与数字文件。", "销毁档案总是正确的选择。", "未来研究者不需要任何档案。"],
          correct: 0,
        },
        {
          id: "c2a-s2",
          type: "sentence",
          eyebrow: "句子理解 · 2/2",
          prompt: "作者为什么说“中立容器”是一种幻想？",
          options: ["档案建筑无法保持恒温。", "选择、描述和保存本身都会塑造记录。", "所有档案都由政府控制。", "只有删除才算干预。"],
          correct: 1,
        },
        {
          id: "c2a-d1",
          type: "discourse",
          eyebrow: "语篇理解 · 1/2",
          prompt: "作者对 deliberate forgetting 的立场是什么？",
          options: ["支持不受限制地销毁档案。", "完全反对任何访问限制。", "认为应在防止掩盖证据与避免永久伤害之间进行可解释治理。", "认为所有记录应自动十年后删除。"],
          correct: 2,
        },
        {
          id: "c2a-d2",
          type: "discourse",
          eyebrow: "语篇理解 · 2/2",
          prompt: "第四段列举违法记录和照片，主要说明什么？",
          options: ["同一记录的价值和风险会因用途与技术变化。", "历史研究一定伤害个人。", "照片比文字档案更可靠。", "统一到期时间最容易解决问题。"],
          correct: 0,
        },
      ],
    },
    {
      id: "c2-b-seamless-explanation",
      version: "B",
      band: "C2",
      title: "Against the seamless explanation",
      dek: "Why a perfectly smooth story may be less truthful than an honest gap.",
      readTime: "约 6 分钟",
      paragraphs: [
        "We often praise an explanation for being seamless. A complicated event is reconstructed as a clean sequence: one condition produced another, a decisive choice redirected the plot, and the eventual outcome appears—if not inevitable—at least intelligible. The satisfaction is genuine. Without some arrangement of cause and consequence, experience would remain an inventory rather than a history.",
        "Yet smoothness can be purchased too cheaply. When an account moves without hesitation from motive to action and from action to result, it may conceal how much of the connection was supplied after the fact. People rarely understand all their reasons while acting; institutions leave incomplete records; accidents amplify minor decisions while neutralising apparently important ones. A narrative can eliminate these uncertainties simply by failing to mention them. Coherence then becomes not the discovery of order but the suppression of resistance.",
        "This is especially visible in stories of success. Once an enterprise prospers, its early improvisations are redescribed as strategy. A fortunate introduction becomes evidence of networking skill; a competitor’s unexpected failure disappears into the background; contradictory decisions are recast as flexible experimentation. None of these claims need be wholly false. The distortion lies in arranging selected truths so that the outcome seems to confirm the qualities now attributed to the winner.",
        "The opposite mistake is to treat every gap as proof that explanation is impossible. Uncertainty does not abolish causation, and modesty is not the same as intellectual surrender. We can distinguish evidence from conjecture, identify several plausible mechanisms and estimate which mattered most. What we should resist is the demand that an account perform certainty it has not earned.",
        "An honest explanation may therefore contain joints that remain visible. It can say that a policy probably contributed to a result without pretending to isolate its exact share; it can acknowledge that participants remember the same meeting differently; it can preserve an unresolved alternative instead of forcing it into a footnote. Such admissions do not necessarily weaken the account. They show the reader where interpretation begins and make later revision possible.",
        "The preference for seamlessness is partly aesthetic and partly institutional. Publishers reward confident narratives, leaders benefit from stories that make authority look purposeful, and audiences understandably prefer a lesson they can carry away. But the desire for usefulness can turn explanation into retrospective instruction: because the past must teach us something, it is made to resemble a curriculum.",
        "A truthful account need not abandon shape. It must, however, prevent shape from impersonating proof. The best explanations are not those in which every loose end vanishes, but those that reveal why some connections are secure, why others remain provisional and what would have to be learned for the pattern to change. Their gaps are not defects in the story. They are part of its evidence.",
      ],
      definitions: {
        intelligible: "可以理解的",
        inventory: "清单；罗列",
        conceal: "掩盖",
        amplify: "放大；增强",
        neutralising: "使失去作用",
        coherence: "连贯性",
        suppression: "压制；有意排除",
        prospers: "成功发展；繁荣",
        distortion: "歪曲",
        conjecture: "推测",
        provisional: "暂定的；可能修正的",
        impersonating: "冒充；假装成为",
      },
      questions: [
        {
          id: "c2b-v1",
          type: "vocabulary",
          eyebrow: "语境词汇 · 1/2",
          prompt: "第二段中的 suppression of resistance 在语境中指什么？",
          options: ["压下不符合顺畅叙事的不确定性和反例", "反对所有历史解释", "让事件发生得更快", "阻止读者阅读成功故事"],
          correct: 0,
        },
        {
          id: "c2b-v2",
          type: "vocabulary",
          eyebrow: "语境词汇 · 2/2",
          prompt: "最后一段中的 provisional connections 指什么？",
          options: ["已经被彻底证明的联系", "暂时成立、仍可能修正的联系", "完全虚假的联系", "与主题无关的联系"],
          correct: 1,
        },
        {
          id: "c2b-s1",
          type: "sentence",
          eyebrow: "句子理解 · 1/2",
          prompt: "“The outcome seems to confirm the qualities now attributed to the winner.” 揭示了什么偏差？",
          options: ["成功后的叙事会选择性重排过去，使胜者品质看似必然导致结果。", "胜者从来没有任何能力。", "竞争者失败总是最重要原因。", "成功故事不能包含真实信息。"],
          correct: 0,
        },
        {
          id: "c2b-s2",
          type: "sentence",
          eyebrow: "句子理解 · 2/2",
          prompt: "“Prevent shape from impersonating proof” 最准确的意思是什么？",
          options: ["解释不应有任何结构。", "叙事的连贯形式不能被当作因果已经得到证明。", "只有图形才可以作为证据。", "所有证据都必须写进脚注。"],
          correct: 1,
        },
        {
          id: "c2b-d1",
          type: "discourse",
          eyebrow: "语篇理解 · 1/2",
          prompt: "作者主张怎样的解释方式？",
          options: ["完全放弃因果和叙事结构。", "提供确定而简单的成功公式。", "保留结构，同时公开证据强弱、不确定性和可修正之处。", "把所有历史都写成资料清单。"],
          correct: 2,
        },
        {
          id: "c2b-d2",
          type: "discourse",
          eyebrow: "语篇理解 · 2/2",
          prompt: "第六段讨论出版者、领导者和受众，主要说明什么？",
          options: ["顺畅解释受到审美和制度激励共同推动。", "出版者拒绝所有自信叙事。", "领导者比历史学家更客观。", "受众无法理解不确定性。"],
          correct: 0,
        },
      ],
    },
  ],
};

export const ALL_TEST_PACKS = Object.values(TEST_PACKS).flat();
